targets:
  $default:
    builders:
      widgetbook_generator:telemetry:
        enabled: false
      slang_build_runner:
        options:
          base_locale: es
          fallback_strategy: base_locale
          input_directory: lib/shared/i18n
          input_file_pattern: .i18n.yaml
          output_directory: lib/shared/i18n
          output_file_name: translations.g.dart
          output_format: single_file
          namespaces: true
          string_interpolation: double_braces
      json_serializable:
        options:
          field_rename: snake

