name: chat_bot_poc
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  bloc: ^8.1.2
  either_dart: ^1.0.0
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.0
  injectable: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  slang: ^3.23.0
  slang_flutter: ^3.23.0
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  meta: any
  flutter_localizations:
    sdk: flutter
  dart_openai: ^5.1.0
  google_generative_ai: ^0.4.3
  dio: any
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.0
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  http_mock_adapter: ^0.6.0
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  slang_build_runner: ^3.23.0
  vector_graphics_compiler: ^1.1.7
flutter:
  uses-material-design: true
  assets:
    - assets/env
    - assets/icons/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21